
[minecraft]
	replace_dolphin = true
	replace_bee = true
	replace_wolf = true
	replace_ocelot = true
	replace_fox = true
	replace_cat = true
	replace_mooshroom = true
	replace_silverfish = true
	replace_squid = true
	replace_polarbear = true
	replace_spider = true
	replace_sheep = true
	replace_cavespider = true
	replace_cow = true
	replace_pig = true
	replace_chicken = true

